BEGIN;

ALTER TABLE product_images
ADD COLUMN IF NOT EXISTS preview_url TEXT DEFAULT '';

ALTER TABLE product_images
ADD COLUMN IF NOT EXISTS position INTEGER DEFAULT 0;

ALTER TABLE product_images
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

COMMIT;
